# version format
version: "{build}"

skip_tags: false

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tests\\run_with_env.cmd"
    PYTHONDONTWRITEBYTECODE: 1

  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"
      ARCH: x86_64

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"
      ARCH: x86_64

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      ARCH: x86_64

install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell tests\\install.ps1"

  # Prepend current Python and scripts dirs to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - '%CMD_IN_ENV% pip install -r tests\requirements\py3.txt'

  # Install GNU gettext toolset
  - set GETTEXT_URL=https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.6-v1.14/gettext0.19.6-iconv1.14-shared-64.exe
  - appveyor DownloadFile %GETTEXT_URL% || (ping -n 10 127.0.0.1 >"nul:" & appveyor DownloadFile %GETTEXT_URL%)
  - gettext0.19.6-iconv1.14-shared-64.exe /VERYSILENT
  - "SET PATH=C:\\Program Files\\gettext-iconv;%PATH%"
  - xgettext --version

build: off

test_script:
  - set PYTHONPATH=%CD%
  - cd tests
  - python runtests.py --verbosity 0
